# **Lecture 4:** Logical Statements and Boolean Operators

### The purpose of todays lecture is to introduce the use of *Logical Statements* and *Boolean Operators* in Programming. 

### A simple definition of a logical statement: 
### A logical statement is a statement that produces an output which either has the value **True** or **False**.  

### From a coding perspective, we could also map those two states onto a binary variable which takes on the value 1 or 0.  
### In practice these two representations can be used interchangeability and implicitly.  

### This type of variable is known as a **Boolean** variable.   

### In this lesson, we will learn how to setup and evaluate various types of logical statements. 

### In scientific appliations in Psychology/Neuroscience we will make use of logical statements to develop boolean variables as 
* #### *masks* to segregate data in data anlysis. 
* #### to control *conditional* code execution.   

In [1]:
import numpy as np
from numpy import random
from matplotlib import pyplot as plt
import pandas as pd

## Comparison Operators

### A logical statement almost always involves comparisons. Examples of comparisons that come to mind might be 
1. #### `==` - equal                    
1. #### `!=` - not equal                
1. #### `>`  - greater than             
1. #### `>=` - greater than or equal    
1. #### `<`  - less than                
1. #### `<=` - less than or equal       

### Example 1  Logical Statements on Variables
### This set of examples looks at simple logical statements on variables, that returns either **True** or **False**

In [2]:
x = 5   #This is a statement defining the variable x with the value 5.  
x == 5   #Test of Equality, returns the value True 

True

In [3]:
test = x == 5  #Equal, True statement, correct syntax, unpleasant formatting 
print(test)
type(test)

True


bool

In [4]:
x = 5
test = (x == 5)  #Equal, True Statement, correct syntax, readable formatting 
print(test)

True


In [5]:
x = 5
test = (x != 5)  #Not Equal, False Statement 
print(test)

False


In [6]:
x = 5
test = (x == 5)  
print(test)
istestone = (test == 1) # Here I test if the boolean vairable true is the same as 1
print(istestone)

True
True


In [7]:
x = 5
test = (x != 5)  #Not Equal, False Statement 
print(test)
istestzero = (test == 0) # Here I test if the boolean vairable true is the same as 1
print(istestzero)

False
True


### Example 2 Logical Statements on numpy arrays 
### When applying logical statements to an array, we return a numpy **Boolean** array of equal size containing Boolean variables.  
### Because the Boolean array is a numpy array, we can do *math* with it.  

In [8]:
x = np.array([1, 2, 3, 4, 5]) #make an array from a list 1,2,3,4,5
print(x)
test = (x < 3)  # use the less than logical operation 
print(test) #print the output of the numpy array 
test.dtype  # with numpy arrays we use the dtype method to find out the data type. 

[1 2 3 4 5]
[ True  True False False False]


dtype('bool')

In [9]:
x = np.array([1, 2, 3, 4, 5]) #make an array from a list 1,2,3,4,5
print(x)
#How many elements of the array are less than 3? 
test = (x < 3)  # use the less than logical operation 
print(test)
nless = np.sum(test) #Here I sum the boolean array, implicitly converting the True to 1 and False to 0
print(nless)

[1 2 3 4 5]
[ True  True False False False]
2


In [10]:
x = np.array([1, 2, 3, 4, 5]) #make an array from a list 1,2,3,4,5
print(x)
#How many elements of the array are less than 3? 
test_less = (x < 3)  # use the less than logical operation 
print(test_less)
test_greater = (x > 3)  # greater than
print(test_greater)

[1 2 3 4 5]
[ True  True False False False]
[False False False  True  True]


In [11]:
x = np.array([1, 2, 3, 4, 5]) #make an array from a list 1,2,3,4,5
print(x)
#How many elements of the array are less than 3? 
test_less = (x < 3)  # use the less than logical operation 
print(test_less)
test_greater_eq = (x >= 3)  # greater than or equal
print(test_greater_eq)

[1 2 3 4 5]
[ True  True False False False]
[False False  True  True  True]


In [12]:
x = np.array([1, 2, 3, 4, 5]) #make an array from a list 1,2,3,4,5
print(x)
test_less_eq = (x <= 3)  # less than or equal
print(test_less_eq)
test_greater = (x > 3)  # greater than
print(test_greater)

[1 2 3 4 5]
[ True  True  True False False]
[False False False  True  True]


In [13]:
x = np.array([1, 2, 3, 4, 5]) #make an array from a list 1,2,3,4,5
print(x)
test_eq = (x == 3)  # equal
print(test_eq)
test_neq = (x != 3)  # not equal
print(test_neq)

[1 2 3 4 5]
[False False  True False False]
[ True  True False  True  True]


### Rules of Logic 1 - Set Theory Perspective

### The rules of logic and set theory are important to understand in meaningfully evaluation logical statements. 

### We can view the array `x =[1 2 3 4 5]` as a **set**. This set defines a **space**, or universe.

### Any of the logical and comparison operations divides the space into two **subspaces**, one where the logical statement is **True**, and another where the logical statement is **False**.    

### **The most important thing to remember is that the True and False subsets must combine to the original set**

### Logical complement, or logical_not

### The complement of a boolean variable is the opposite state.  The complement of **True** is **False** and the complement of **False** is **True** 

### There are two ways to take the complement of a Boolean array.  One is the numpy method `logical_not` or by using the operator `~`


In [14]:
x = np.array([1, 2, 3, 4, 5]) #make an array from a list 1,2,3,4,5
print(x)
test_greater = (x > 3)  # greater than
test_not_greater = np.logical_not(test_greater)
print('test greater = ', test_greater)
print('test greater complement  = ',test_not_greater)

[1 2 3 4 5]
test greater =  [False False False  True  True]
test greater complement  =  [ True  True  True False False]


In [ ]:
x = np.array([1, 2, 3, 4, 5]) #make an array from a list 1,2,3,4,5
print(x)
test_equal = (x == 3)  # greater than
test_not_equal = ~test_equal
print('test equal  = ', test_equal)
print('test equal complement  = ',test_not_equal)

### Manual Entry of a  Boolean Variable or Array 

### Sometimes we need to manually create Boolean variable or array.  There are two easy ways to do this 


In [15]:
#Boolean variables
boolean_var1 = True
print(boolean_var1)
boolean_var2 = bool(0)
print(boolean_var2)

True
False


In [16]:
#Boolean Arrays
boolean_array1 = [True,False,False,True]
print(boolean_array1)
boolean_numpy_array1 = np.array(boolean_array1)
print(boolean_numpy_array1)

[True, False, False, True]
[ True False False  True]


In [17]:
#Boolean arrays from 0 and 1
integer_array = np.array([0,1,1,0])
print(integer_array)
boolean_array3 = np.array([0,1,1,0],dtype=bool)  # force the data type to boolean 
print(boolean_array3)

[0 1 1 0]
[False  True  True False]


### Conversion to a Boolean Array - Can I turn anything into a boolean array. 
### What are the rules? 
1. #### 0, None, False or empty strings ARE **False**
2. #### Values other than 0, None, False or empty strings ARE **True**.

In [18]:
strange_list = [1, 0.5, 0, 0.0, None, 'a', '', ' ',True, False]
bool_arr = np.array(strange_list, dtype=bool)
print(strange_list)
print(bool_arr)

[1, 0.5, 0, 0.0, None, 'a', '', ' ', True, False]
[ True  True False False False  True False  True  True False]


### Interpreted languages like Python, Matlab, R are easy to use because you can be careless like this and things still kind of work.  

### **This is their strength AND their weakness**

### Its really easy to have a mistake in your code and have your code seem to work in these languages.  

### Logical Operators to Compare Arrays

### Logical Operators can be used to compare arrays of equal size and shape.  
### Such comparisons proceed on an element by element basis and return a Boolean array 

In [19]:
rng = random.default_rng(seed = 21)
array_a = rng.integers(0,10,8) #array of random integers
array_b = rng.integers(0,10,8)
test = (array_a > array_b) # is a greater than b
print(array_a)
print(array_b)
print(test)

[3 7 3 6 4 7 3 0]
[2 6 6 9 2 4 9 1]
[ True  True False False  True  True False False]


In [20]:
### You can embed mathematical calculations into logical statements. 
x = np.array([1,2,3,4,5])
y = 2**x
z = x**2
test = (y == z)
print(x)
print(y)
print(z)
print(test)
onesteptest = (2**x == x**2)
print(onesteptest)



[1 2 3 4 5]
[ 2  4  8 16 32]
[ 1  4  9 16 25]
[False  True False  True False]
[False  True False  True False]


## Boolean Operators 

### Here I introduce the use of combinations of Logical Statements using **Boolean operators** to express more complex logical expressions. 
### Boolean Operators are operators that work on Boolean variables to create **compound** logical statements.  

### This is equivalent to the idea arithmetic operators are operators that work on floating point numbers. 


###  `Not` (`~`) operator


### We already introduced one Boolean operator with is ~ (NOT).  This Boolean operator flipped the value of the Boolean variable between True and False. 


In [ ]:
bool_array1 = np.array([0,0,0,1,1,0,1,0],dtype=bool)
print(bool_array1)
bool_array2 = ~bool_array1
print(bool_array2)

### Table of Boolean Operators.

### The following table summarizes the bitwise Boolean operators and their equivalent ufuncs:

### There are 3 logical operators: `and`, `or`, `not` <br>

<table><tbody><tr><th>Operator</th>
			<th>Meaning</th>
			<th>Example</th>
		</tr><tr><td>and</td>
			<td>True if both the operands are true</td>
			<td>x & y</td>
		</tr><tr><td>or </td>
			<td>True if either of the operands is true</td>
			<td>x | y</td>
		</tr><tr><td>not</td>
			<td>True if operand is false (complements the operand)</td>
			<td>~x</td>
		</tr></tbody></table>

### **VERY IMPORTANT POINT**

### You will read online about the `and` and `or` operators built in to python. 
### Many students have wasted a lot of time trying to use this to discover that they dont work as expected. 
### Please use `&` for and `|` for or


### Combining Boolean operators on arrays can lead to a wide range of efficient logical operations

### Example 1 - & (AND)

In [22]:
rng = random.default_rng(seed = 1967)
a = rng.integers(-9,10,12) #make integers from -9 to 9 
print(a)
x = (a < 5) #find the integers less than 5
print('x = ',x) #This is a Boolean which tells where in a I can find x
y = (a > -5) #find the integers greater than -5
print('y = ',y) #This is a Boolean which tells me where in a I can find y 

[ 3  9  4  5 -1 -5 -1 -2  0 -9  1 -7]
x =  [ True False  True False  True  True  True  True  True  True  True  True]
y =  [ True  True  True  True  True False  True  True  True False  True False]


### To find the integers between -5 and 5 we need to take the **intersection** 
### of the subset of a represented by x with the subset of a represented by y. 
### In math, we would write this is as $x \cap y$
### In logic, this is known as an **and** operation.
### In python, we can carry this out with an `&` operator

In [23]:
z1 = x & y #The & symbol requires that both conditional statements be true 
print(z1)

[ True False  True False  True False  True  True  True False  True False]


### Example 2 - | (OR)

In [24]:
a = rng.integers(-9,10,12) #make integers from -9 to 9 
print(a)
x = (a > 5) #find the integers greater than 6
print('x = ',x) #This is a Boolean which tells where in a I can find x
y = (a < -5) #find the integers less than -6
print('y = ',y) #This is a Boolean which tells me where in a I can find y 

[ 6  2  8 -3  5 -8  0  5  2 -4  8 -8]
x =  [ True False  True False False False False False False False  True False]
y =  [False False False False False  True False False False False False  True]


### To find the integers *either* greater than 6 *or* less than -6 we need to take the **union** of the subset of a represented by x with the subset of a represented by y. 
### In math, we would write this is as $x \cup y$
### In logic, this is known as an **or** operation.
### In python, we can carry this out with an `|` operator

In [25]:
z1 = (x | y) #The | symbol requires that either one of the conditional statements be true 
print(z1)

[ True False  True False False  True False False False False  True  True]


## Working with Boolean Arrays

### Why do we want to make use of Boolean arrays?  
### Here I will show some useful operations that Boolean arrays will allow us to do.  And then, I will show an example of how we make use of Boolean to organize data.  

### Counting entries

### To count the number of **True** entries in a Boolean array, `np.count_nonzero` is useful:

In [26]:
x = rng.integers(0,9,12)
print(x)
print(x<6)
# how many values less than 6?
n6 = np.count_nonzero(x < 6)
print(n6)

[8 5 4 3 0 3 5 8 6 7 4 8]
[False  True  True  True  True  True  True False False False  True False]
7


### We see that `count_nonzero` counted the number of entries that were **True** in the entire matrix. 
### Python interprets **True** as having the numeric value of 1, and **False** as zero.  
### Another way to get at this information is to use `np.sum`:

In [27]:
nsum6 = np.sum(x < 6)
print(nsum6)

7


### Any and All for global array tests
### `np.any` and `np.all` can be used to test the entire array for whether *any* element is **True** or *all* elements are true 


In [28]:
# are there any values greater than 8?
print(x)
np.any(x > 8)

[8 5 4 3 0 3 5 8 6 7 4 8]


False

In [29]:
# are there any values less than zero?
print(x)
np.any(x < 0)

[8 5 4 3 0 3 5 8 6 7 4 8]


False

In [30]:
# are all values less than 10?
print(x)
np.all(x < 10)

[8 5 4 3 0 3 5 8 6 7 4 8]


True

In [ ]:
# are all values equal to 6?
print(x)
np.all(x == 6)

### Boolean Indexing 

### We can make use of the Boolean variable that is the results of a logical statement as the **index** into a variable to extract the variables that meet the condition of the logical statement.   

### We often will want to return the **index** into an array that meets a logical condition. 

In [ ]:
my_array = rng.integers(0,10,20)
print(my_array)
#test if the array entries are bigger than 5
test = (my_array > 5)
print(test)
#how many values are there greater than 5 
count = np.sum(test)
print(count)
my_greater_than_5_array = my_array[test]
print(my_greater_than_5_array)
np.size(my_greater_than_5_array)

### Suppose my task is to find the mean of all entries in the array greater than 5. 
### I can do this with a simple logical statement.  
### Its really important to look at this and see it in spoken language terms. 

In [ ]:
bigmean = np.mean(my_array[my_array > 5])
print(bigmean)
                  

## Organizing Data with Boolean Arrays 

### Data is rarely delivered to you in the organized in the manner that you want for data analysis. 

### For example,consider a behavioral experiment with *3* conditions.  In a typical experimental protocol, the subject will be presented a random condition on each trial. The subjects response will be recorded on each trial. 

### We might then at the end expect to have a data file, where the data has been recorded continuously in the experiment IN THE ORDER OF EXPERIMENT, not organized by condition.  

In [31]:
rtdata = pd.read_excel('rtdata.xlsx')
rtdata.keys()

Index(['Unnamed: 0', 'trialnumber', 'condition', 'responsetime'], dtype='object')

In [32]:
print(rtdata)

     Unnamed: 0  trialnumber  condition  responsetime
0             0            0          3      1.647837
1             1            1          3      1.184691
2             2            2          2      0.958936
3             3            3          2      0.987493
4             4            4          1      0.795122
..          ...          ...        ...           ...
145         145          145          1      0.864931
146         146          146          1      0.845103
147         147          147          3      1.355779
148         148          148          1      0.970600
149         149          149          3      1.264055

[150 rows x 4 columns]


### Before we get started, lets copy the values from the DataFrame to variables 
### I always go ahead and convert them into numpy arrays 

In [33]:
trialnumber = np.array(rtdata['trialnumber'])
condition = np.array(rtdata['condition'])
responsetime = np.array(rtdata['responsetime'])


### `unique` values

### Now, it would be quite useful to know how many conditions there are.  From looking at the output of print, you might think there are 3 - 1,2,3.  But only 10 values are displayed here.  

### A really useful function in numpy is `unique`

In [34]:
the_conditions = np.unique(condition)
print(the_conditions)

[1 2 3]


### TASK: Compute the mean response time for each condition.  

### USE LOGICAL STATEMENTS TO CREATE BOOLEAN VARIABLES THAT IDENTIFY THE TRIALS CORRESPONDING TO EACH CONDITION.   

In [35]:
rt1 = np.mean(responsetime[condition == 1])
rt2 = np.mean(responsetime[condition == 2])
rt3 = np.mean(responsetime[condition == 3])
rt = [rt1,rt2,rt3]
print(rt)

[1.015639981051043, 1.1043193554147697, 1.2307592896048725]
