# **Lecture 2**: Numpy Module for Scientific Computing: Arrays and Math Functions 

## Python Modules

### Python is organized around **modules**. A module is a collection of *functions* or *classes*, that are grouped together. 

### For now, you can think of a function or a class as some program that already exists, that you can make use of for your program, by *calling* the function or class.  

### Some widely used modules and what they stand for 

1. ####  `numpy` - Numerical functions for Python

1. ####  `scipy` - Scientific functions for Python, including engineering and statistics methods.  

1. ####  `sklearn` - Data science and related statistical methods

1. ####  '`pandas` - File input, output and data organization methods. 

1. ####  `matplotlib` - Plotting and Data Visualization functions. 

### How do I learn more about this.  Google is your friend. 


## Functions and Classes 

### A **function** is a specialized operation that has been programmed to take one or more *input* variables and return one or more *output* variables.  

### When your call a function, you will write a line of code that looks something like this 

`output_variables =  function_name(input_variables)`

### There can be more than one output_variables, and more than one input_variables, separated by commas. 

### A Class is a template to create an **object** that has **methods** associated with it.

`output_variables = object.method(input_variables)`


## Numpy 

### The `numpy` **module** is used in almost all numerical computation using Python.  I do not think I have ever written a program without numpy.  

### It is a package that provide high-performance vector, matrix and even higher-dimensional data structures for Python. 

### Underneath the hood, it is implemented in C and Fortran so performance is very good. You can't write anything faster.  

### To use `numpy` you need to import the module, **sub-module** , or a specific **function** inside a module or submodile.  


## Import the numpy module

### Because `numpy` is so generally useful, we usually import the entire numpy module.  There are two ways to do this:

### `import numpy`

### This tells python to import `numpy`

### `import numpy as np`

### This tells python to import the `numpy` module and use the abbreviation `np` to refer to it in the code. This is convenient as we concatenate function names as `np.function`.  

### Note that you could have called it whatever you want.  `np` is widely used as an abbreviation for `numpy`. 


In [2]:
import numpy as np

## Creating `numpy` arrays

### In the `numpy` module the basic data type is an **array**. 

### Working with an array is a lot like working with a list, but arrays are more disciplined, so we can do more with them. 

### The critically important property is: **Arrays only have 1 data type**


### There are a number of ways to initialize new numpy arrays, for example from
1.  using functions that are dedicated to generating numpy arrays, such as `arange`, `linspace`
1.  creating an array filled with the same value at every entry using functions such as `zeros` or `ones`
1.  creating an array filled with random numbers using functions such as `random`
### In working with data we will learn also how to create numpy arrays by 
1. reading data from different types of files
1.  converting a Python list or tuples, using functions such as `array`

## Initializing an array of zeros

## Probably the most common way to create an array is to initialize all the elements of the array with the value 0. 

### This can be done with the function `zeros`. 

### A function takes input arguments 

### To invoke this function use `np.zeros`. I refer to it as `zeros` as it is the function `zeros` in the `np` module.

### In principle, there could be another function called zeros in another module.  Specifying the module avoids confusion.  

### I need to also decide on the size of the array.  In this example below i initialize an array called my_array with 5 elements, all of which have the value 0.  


In [11]:
my_array = np.zeros(5)
print(my_array)
type(my_array)

[0. 0. 0. 0. 0.]


numpy.ndarray

### Notice that the array is floating point and not integer. The type of variable is a numpy.ndarray

### An array with 2 dimensions is called a matrix.  Lets initialize a  matrix

In [12]:
my_array2 = np.zeros((3,4))
print(my_array2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### Now I'm going to initialize a slightly different array.  This is an array which has two dimensions.  It has 1 row and 5 columns. 

In [13]:
my_matrix = np.zeros((1,5))
print(my_matrix)

[[0. 0. 0. 0. 0.]]


## Checking the type of array.  
### The `type` function in python will tell us what type of variable is my_array

In [10]:
print(type(my_array))
print(type(my_array2))
print(type(my_matrix))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


## Examining Array Size, Shape, and Data Type
### Arrays generated with numpy have built in `methods`.  Some of these methods return properties of the arrays, and some of them can be used to manipulate the array
###
* `shape` tells us the shape of an array
* `size` tells us the total number of elements in an array 
* `dtype` query the array for the type of data contained in it.

In [ ]:
#array shape
array_shape = my_array.shape
print(array_shape)
array2_shape = my_array2.shape
print(array2_shape)
matrix_shape = my_matrix.shape
print(matrix_shape)

In [ ]:
#array size
array_size = my_array.size
print(array_size)
array2_size = my_array.size
print(array_size)
matrix_size = my_matrix.size
print(matrix_size)

In [15]:
### Alternatively, you could obtain the same information by using the corresponding `numpy` functions
array2_shape = np.shape(my_array2)
print(array2_shape)
array2_size = np.size(my_array2)
print(array2_size)
### But its a good idea to gain some experience with the object-oriented syntax, because some things cannot be done without it.  

(3, 4)
12


In [16]:
#dtype is only available as an object method
print(my_array2.dtype)

float64


### We made a matrix of zeros.  zeros could have been integers, but they can also be floating point numbers. 

### notice that instead of `float` it specifies the type as `float64`.  This refers the precision of the computer on which you are doing calculations.   

### We usually don't worry about the bit-size and let python go to its default which is usually 64 bit on modern computers.  

### However, there are some times you have to pay attention to it, that usually involves data that comes from an external source.  

### One example is in handling images, where the number of bits controls the degree of specificity in color, etc of an image. 

### Another example comes from measuring physiological signals while doing behavioral experiments.  In this case, the devices are constrained by acquisistion speed, and may limit the resolution to 16 bits.  


## Initializing an array of ones or any arbitrary value.
### Similar to the function `zeros` numpy has a function called `ones`
### You can use it to make arrays containing arbitrary values
### An array of ones can be multiplied by an arbitrary constant to make an array of that value. 

In [17]:
my_one_array = np.ones(4)
print(my_one_array)
my_fives_array = 5*np.ones(10)
print(my_fives_array)

[1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## Array-generating functions
### `zeros` and `ones` are examples of array generating function, which populates an array of user specified size with the value zero or one respectively.  
### There are a number of very useful array generating functions in the numpy module.
### We will introduce the 2 of the most important ones here:
### * `arange` - creates a range of linearly spaced values specifying interval
### * `linspace` - lineary spaced values specifying number of values

### `arange` creates an array containing values from a starting point to an ending point with a user specified step. 

###  **The ending point is not included in the array.**  

In [18]:
# create a range
#using arange the stop point IS NOT included
x = np.arange(0, 10, 1) # arguments: start, stop, step
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [19]:
y = np.arange(-4, 4.01, 0.5)  #notice I stopped it at 4.01 instead of 4.  
print(y)

[-4.  -3.5 -3.  -2.5 -2.  -1.5 -1.  -0.5  0.   0.5  1.   1.5  2.   2.5
  3.   3.5  4. ]


### `linspace` creates an array from a starting point to an ending point, with the number of points specified by the user rather than the step.  

### **The ending point is included in the array** 

In [23]:
# using linspace, both end points ARE included
z = np.linspace(0, 10, 26) #arguments: start, stop, number of points
print(z)

[ 0.   0.4  0.8  1.2  1.6  2.   2.4  2.8  3.2  3.6  4.   4.4  4.8  5.2
  5.6  6.   6.4  6.8  7.2  7.6  8.   8.4  8.8  9.2  9.6 10. ]


In [24]:
np.shape(z)

(26,)

## Converting other data types into an array

### The function `array` can be used to convert other data types into arrays. 

### The most common use is to convert a **list** into a **ndarray** 


In [29]:
my_list = [1,2,3]
print('my_list = ', my_list)
my_array = np.array(my_list)
print('my_array = ',my_array)
# Notice that the list is separated by commas while arrays are separated by spaces.   

my_list =  [1, 2, 3]
my_array =  [1 2 3]


In [30]:
my_list = [2.0,2.1,13]
print('my_list = ', my_list)
my_array = np.array(my_list)
print('my_array = ',my_array)
# Notice that in this example my list had two floating point numbers and 1 integer.  By default, it will convert the integer into a floating point because an array can only have 1 data type.  

my_list =  [2.0, 2.1, 13]
my_array =  [ 2.   2.1 13. ]


In [32]:
my_kawhi_list = ['Kawhi','Leonard','June',29,1991,79.0]
print('my_kawhi_list = ', my_list)
my_kawhi_array = np.array(my_kawhi_list)
print('my_kawhi_array = ',my_kawhi_array)
#Notice that the presence of a string converts all of the elements of the list into an array of strings. 

my_kawhi_list =  [2.0, 2.1, 13]
my_kawhi_array =  ['Kawhi' 'Leonard' 'June' '29' '1991' '79.0']


##  Mathematical Functions in numpy

### Numpy has built in a large number of mathematical functions.  

### Basic Math
### Of course the basic operations will work on numpy arrays, element by element:
* +, addition                                  
* -, subtraction
* \*, multiplication
* / division 
* \*\*, exponentiation 
* //, floor division or integer division 
* %, remainder 
### **THEY WILL ONLY WORK WITH A SCALAR NUMBER OR WITH ARRAYS OF THE SAME SIZE**

In [34]:
a = np.array([0.5, 1,2])
b = np.array([4,6,8]) 
c = np.array([-1,1])
print(a)
print(b)
print(c)
#lets test the operations above. 

[0.5 1.  2. ]
[4 6 8]
[-1  1]


### Arithmetic with scalar numbers. 
### We can use the usual arithmetic operators to multiply, add, subtract, and divide arrays with scalar numbers.


In [35]:
print(b)
add = b+2 
print(add)
subtract = b-2
print(subtract)
multiply = b*2
print(multiply)
divide = b/2 
print(divide)


[4 6 8]
[ 6  8 10]
[2 4 6]
[ 8 12 16]
[2. 3. 4.]


### This is just a self exercise, to make sure you are comfortable with doing basic math operations. 
## verify what happens when you do 
*   a+b
*   a-b
*   a*b
*   a/b
*   a**2
*   b/3
*   b//3
*   b%3 
### You dont need to submit these responses.  Just do it for yourself in the box below. 
### Also confirm you cannot do this 
*   a+c
### This is because the arrays do not match in size.  


### 2.2.2 Manipulating Sign and Data Type
### There are also some basic manipulation of the sign and type of data:
* `abs`, computes the absolute value
* `rint`, rounds to the nearest integer
* `floor`, discard the decimal and return integer value  
* `ceil`, return the first integer higher than the number
* `sign`, returns -1 for negative values and 1 for positive values 

In [40]:
c = np.array([-1.75, -0.75, -0.5, 0, 0.5, 0.75, 1.75])
print(c)
#let's test the operations above
print('abs',np.abs(c))
print('rint',np.rint(c))
print('floor',np.floor(c))
print('ceil',np.ceil(c))
print('sign',np.sign(c))

[-1.75 -0.75 -0.5   0.    0.5   0.75  1.75]
abs [1.75 0.75 0.5  0.   0.5  0.75 1.75]
rint [-2. -1. -0.  0.  0.  1.  2.]
floor [-2. -1. -1.  0.  0.  0.  1.]
ceil [-1. -0. -0.  0.  1.  1.  2.]
sign [-1. -1. -1.  0.  1.  1.  1.]
