# **Tutorial**  Random Numbers and Array Methods 

# Random Numbers 

### A random number is an important concept in programming for scientific research.   Random numbers are used in 

1. #### Stimulus Generation (Adding noise to hide or occlude stimuli in an experiment).

2. #### Experimental Control (Randomization of experiments within an experiments and across participants). 

3. #### Simulation and Modeling of data.

### A classic definition of a random number is a number that cannot be predicted. 

### Usually we have a more narrow definition of a random number, which is tied to the way that we generate random numbers.  

## Random Number Generators

### Random number generation is a process by which, often by means of a random number **Generator** object, a sequence of numbers or symbols that cannot be reasonably predicted better than by random chance is generated. 

### Some of these have existed since ancient times, among whose ranks are well-known "classic" examples, including the rolling of dice or coin flipping, the shuffling of playing cards.  

### I am going make use of random numbers here today just to make examples on how to handle arrays, and how to use numpy functions. 

### **Importantly, I will show you here how to make random number sequences that you can reproduce** - It's random, but it's not! 


### Let's begin by importing the modules that we need.  

In [1]:
import numpy as np 

### Now I'm going to use a somewhat different form of importing

`from numpy import random`

### In the above line I import the specific **submodule** `random` from **numpy**.  

### I do this because I dont want to write `np.random` over and over again in my program and I just want to write `random`. 

### This is because I am going to call functions or methods from the submodule `random``.  This would lead to awkward constructs like 

`np.random.function_name`

### I want to be able to not type np every time.  

### `numpy` has a *lot* of built in functions.   More than I know! 

### They are organized into **submodules** that group together functions of a particular type.  Here there is a submodule `random` which has all the random number generators in python.   

### You can always import submodules and specific functions by name to avoid having to write out the module or submodule they come from.  

In [2]:
from numpy import random 

## Create and *Initialize* the random number generator

### In this example create a random number generator object **rng** using the method `default_rng`.  
### In order to control the random number generator we will set the **seed** of the random number generator.
### The **seed** of the random number generator controls the random number sequence generated.  *If you enter the same seed, you will get the same sequence*
### The **seed** of a random number generator is any integer


In [3]:
#set the seed for the random number generator
myseed = 1234
#create the random number generator object
rng = random.default_rng(seed = myseed)
### Take a look at the Variable Inspector.  A fundamentally new data type has been created, called a **Generator**

## Random Integers

### In order to generate integers, we can use the method `integers`.  To use this method, we have to specify,
### `my_integers = `rng.integers`(low,high,size)` 
### Here low is the lowest integer (inclusive), high is the highest integers (exclusive) and size is the dimensions of the numpy array to be created.  

In [4]:
rint1 = rng.integers(1,7,10)
print(rint1)

[6 6 6 3 2 6 1 2 1 2]


### The output is what you might see if you rolled 10 different 6 sided die.
### Let's run it again.   

In [5]:
rint2 = rng.integers(1,7,10)
print(rint2)

[4 1 5 2 5 2 5 6 6 2]


### Naturally, since these are random numbers, mimicking die rolls, I get different numbers. 

### What happens if I reset the random number seed. 

In [6]:
myseed = 1234
rng = random.default_rng(seed = myseed)
rint3 = rng.integers(1,7,10)
print('rint3: ',rint3)
print('rint1: ',rint1)

rint3:  [6 6 6 3 2 6 1 2 1 2]
rint1:  [6 6 6 3 2 6 1 2 1 2]


### The random numbers I get are identical to the first set!
### At first, this may seem disturbing and certainly not at all *random*
### The way to think about it is that there is an infinite sequence of die rolls.  The seed selects where in the sequence I start to get numbers. 

### Now let's create an array with 5 random numbers between 0 and 9 or between -10 and 10

In [7]:
rdec = rng.integers(0,10,5)
print(rdec)
### Lets not forget integers can be negative. 
rdec2 = rng.integers(-10,11,5)
print(rdec2)

[5 1 7 2 7]
[-4  6 10 10 -5]


### I can also create a higher dimensional array like a matrix, by passing a **tuple** for the dimension of the array. 

In [8]:
# If i want a matrix with 4 rows and 3 columns instead of a vector of 5 numbers, I should provide a tuple (4,3) instead of 5.
rmat = rng.integers(0,10,(4,3))
print(rmat)

[[5 4 2]
 [6 8 8]
 [6 8 5]
 [6 9 6]]


## Random floating point numbers from a uniform distribution

### In order to generate floating point numbers from a uniform distribution, we can use the method `uniform`.  To use this method to create an array **runiform**, we have to specify, 

### runiform = `rng.uniform`(low,high,size)

### These are floating point numbers (real-valued) ranging low (inclusive) to high (exclusive) but can take any value in between with **equal probability**

In [9]:
runiform = rng.uniform(0,1,10)
print(runiform)

[0.7357577  0.22275366 0.17206618 0.87041497 0.06013866 0.68368891
 0.67123802 0.61101798 0.06013731 0.97776927]


### We can increase the range, and incorporate positive and negative numbers

In [10]:
runiform2 = rng.uniform(-5,5,10)
print(runiform2)

[-0.61048373  0.32595022 -4.96867713 -2.48732895  3.58490437 -0.74701649
  2.35818994  4.22043217 -3.46525829  4.92259229]


### And we can specify a matrix with dimensions in a tuple. Here we make a matrix of size 3 rows and 5 columns. 

In [11]:
runiform_mat = rng.uniform(-5,5,(3,5))
print(runiform_mat)

[[-3.17668217  4.40112902 -4.13116945 -0.31789285  3.289892  ]
 [-2.18947737  3.69091511  4.76416574  3.41713657 -0.511264  ]
 [-1.2949157  -0.17330563 -4.07818453 -2.73316895  0.36566237]]


### There are many more ways to generate random numbers.  
### The method `normal`, which draws random numbers from a normal distribution, is also useful.  

# Manipulating Arrays

### Indexing
### We can index elements in an array using square brackets and indices just like lists. 
### The most *challenging/irritating/annoying/exasperating* aspect of indexing is ALWAYS remembering that python 
### **starts counting at 0**
### I am going to first make a vector and a matrix of *random* integers in order to facilitate understanding indexing. 


In [12]:
# v is a vector, and has only one dimension, taking one index

v = rng.integers(-7,7,20)
print('v=', v)

# M is a matrix, or a 2 dimensional array, taking two indices 

M = rng.integers(1,7,(3,4))
print('M=', M)

v= [-5  3 -5 -1  1 -3  2  6 -3  3 -4 -1 -6 -1  2  3 -3  4  0 -3]
M= [[2 5 4 5]
 [5 6 2 1]
 [3 4 5 4]]


In [13]:
### To extract a specific value of v, I have to use and index.  Let's grab the 5th value of v
h = v[4]
print(h)
print(v)
#Verify you got the 5th element.  

1
[-5  3 -5 -1  1 -3  2  6 -3  3 -4 -1 -6 -1  2  3 -3  4  0 -3]


### One of the reasons we use indexing is to place values at a location in an array. 
### If I want to place the number -10 in the 3rd entry of v: 

In [14]:
print(v)
v[2] = -9
print(v) 

[-5  3 -5 -1  1 -3  2  6 -3  3 -4 -1 -6 -1  2  3 -3  4  0 -3]
[-5  3 -9 -1  1 -3  2  6 -3  3 -4 -1 -6 -1  2  3 -3  4  0 -3]


### To index into a matrix M, I  provide a **row** index and **column** index. 
### In order to get the entry 2nd row and 3rd column, I have to index M as M[1,2]

In [15]:
print(M)
m23 = M[1,2] #entry at row 2, column 3 
print('m23: ', m23)
m11 = M[0,0] #first entry of a 3 x 4 matrix 
print('m11: ', m11)
m34 = M[2,3] #last entry of a 3 x 4 matrix
print('m34: ',m34)

[[2 5 4 5]
 [5 6 2 1]
 [3 4 5 4]]
m23:  2
m11:  2
m34:  4


### Of course, if I go out of range, python will just complain.  

In [16]:
M[3,4]

IndexError: index 3 is out of bounds for axis 0 with size 3

### We can address a single row or column of the matrix by 

In [17]:
print(M)
M2 = M[1]
print('M2: ', M2)

[[2 5 4 5]
 [5 6 2 1]
 [3 4 5 4]]
M2:  [5 6 2 1]


### In my opinion, the above is very poor syntax because it is ambiguous which axis you are referring to. 

### It requires that you know that python defaults to rows, and that a single index will extract that row.  

### The same thing can be achieved with more clarity using `:` to indicate *ALL ELEMENTS* 

In [18]:
R2 = M[1,:] # row 2
C1 = M[:,0] # column 1
print(M)
print('R2: ',R2)
print('C1: ',C1)

[[2 5 4 5]
 [5 6 2 1]
 [3 4 5 4]]
R2:  [5 6 2 1]
C1:  [2 5 3]


In [19]:
## I can extract a row and column of a matrix into a new array and do some math on it. 
m = M[:,0]  # I grabbed the first column of M and copied it into m 
u = m**2 - 5 # I squared the values and subtracted v and placed in a new array u
print(u)

[-1 20  4]


In [20]:
# I can manipulate a specific row or column in the matrix 
print(M)
M[:,0] = u #replace the first column with u
M[:,1] = -10 #replace the second column with -10 at all locations
print(M)

[[2 5 4 5]
 [5 6 2 1]
 [3 4 5 4]]
[[ -1 -10   4   5]
 [ 20 -10   2   1]
 [  4 -10   5   4]]


### Size matters!


In [21]:
### Each row of M has 4 elements. If I try to place a vector length other than 4 into a row of M it will fail
v = np.array([1,2,3])
M[0,:] = v

ValueError: could not broadcast input array from shape (3,) into shape (4,)

In [22]:
## IF the size matches, I will succeed. 
v = np.array([1,2,3,4])
M[0,:] = v

## Index slicing 

### Index slicing is the technical name for the syntax `v[lower:upper:step]` to extract part of an array:

In [23]:
A = rng.integers(0,10,8)
print(A)
a = A[1:3] #notice it is inclusive of the lower bound and exclusive of the upper bound
       #also notice I did not specifiy a step, so it defaulted to 1. 
print(a)

[7 2 1 4 2 5 6 9]
[2 1]


In [24]:
print(A)
b = A[6:8]  # notice a weird bit of syntax here A[8] does not exist, but i can write A[6:8] because it excludes 8
print(b)

[7 2 1 4 2 5 6 9]
[6 9]


In [25]:
print(A)
c = A[1:7:2]  #In this example, i use step of size 2. Since my upper bound is 7, index 7 is excluded 
print(c)

[7 2 1 4 2 5 6 9]
[2 4 5]


In [26]:
# We can modify this set of entries in the array if we correctly match the dimensions
print(A)
newvalues = np.array([-5,-10,-15]) # I made a new array from a list 
A[1:7:2] = newvalues
print(A)

[7 2 1 4 2 5 6 9]
[  7  -5   1 -10   2 -15   6   9]


In [ ]:
# We can even make a new call to rng and get new random integers.
print(A)
A[0:2] = rng.integers(-100,-90,2)  # get 2 integers between -100 and -90 and place them in A as the first 2 entries
print(A)

### Arrays strictly control data type. 

### First, lets make an array of of integers and an array of uniform random numbers.  

In [27]:
A = rng.integers(0,10,7)
print(A)
B = rng.uniform(-5,0,3)
print(B)

[7 0 6 2 4 2 0]
[-4.73499019 -3.36752752 -4.00820896]


In [28]:
## Now lets copy B into our integer array A , starting at the 3rd entry to the 5th entry 
print(A[3:6])  # print out the current values of A from the 3rd to 5th entry
A[3:6] = B  # replace these with B 
print(B)
print(A[3:6]) #print new values in A 

[2 4 2]
[-4.73499019 -3.36752752 -4.00820896]
[-4 -3 -4]


### A is an integer array.  If you place floating point numbers in A, it will **crop** the decimal values.  
### When you create an array, it has a data type, and when you put something into the array it will convert it to that data type.  
### When you create an array you can force its data type. 

In [29]:
lst = [1,2,3]
lst_int = np.array(lst)
lst_float = np.array(lst,dtype='float')
print(lst)
print(lst_int)
print(lst_float)

[1, 2, 3]
[1 2 3]
[1. 2. 3.]


### Index slicing in matrices

In [30]:
B = rng.integers(1,7,(7,7))
print(B)

[[3 1 5 4 4 3 1]
 [1 2 1 5 3 1 3]
 [6 1 1 6 5 1 3]
 [6 2 5 2 6 6 4]
 [3 6 1 2 1 3 3]
 [5 6 4 3 6 5 2]
 [6 3 1 4 2 2 4]]


In [31]:
# a block from the original array
C = B[0:2, 1:3]
print(C)

[[1 5]
 [2 1]]


## The concept **axis**?  

### I referred to the rows and columns of m.  Python thinks of these as the **axis** of the array. 
1. #### axis 0 is the rows
1. #### axis 1 is the columns
1. #### axis 2 is the ????  ...
### There is no limit to the number of dimensions to a python array.   Right now we are working with vectors and matrices.  
### But, in many practical applications we need more than 2 dimensions.   
### For example, when we record brain images from human subject, each image has 3 dimensions, and there is a 4th dimension of time.